services:

  mariadb:
    container_name: db
    build:
      context: requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    expose:
      - "3306"
    restart: always
    env_file: .env
    networks:
      mysql:
        aliases:
          - $DATABASE_HOST
    volumes:
      - db_data:/var/lib/mysql

  vsftpd:
    container_name: ftp
    build:
      context: requirements/vsftpd
      args:
        - CERTS_SUBJECT
        - VSFTPD_PASV_PORT_MIN
        - VSFTPD_PASV_PORT_MAX
    expose:
      - "20"
      - "21"
      - "$VSFTPD_PASV_PORT_MIN-$VSFTPD_PASV_PORT_MAX"
    ports:
      - "20:20"
      - "21:21"
      - "$VSFTPD_PASV_PORT_MIN-$VSFTPD_PASV_PORT_MAX:$VSFTPD_PASV_PORT_MIN-$VSFTPD_PASV_PORT_MAX"
    restart: always
    env_file: .env
    networks:
      www:
        aliases:
          - $FTP_HOST
    volumes:
      - wordpress_data:/var/www

  redis:
    container_name: cache
    build: requirements/redis
    expose:
      - "6379"
    restart: always
    networks:
      redis:
        aliases:
          - $CACHE_HOST

  gitea:
    container_name: git
    build: requirements/gitea
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - git_data:/var/lib/gitea

  wordpress:
    container_name: blog
    build: requirements/wordpress
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    env_file: .env
    networks:
      mysql: {}
      redis: {}
      www:
        aliases:
          - $PHP_FCGI_HOST
    volumes:
      - wordpress_data:/var/www

  nginx:
    container_name: http
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME
        - CERTS_SUBJECT
        - NGINX_FCGI_HOST
    ports:
      - "443:443"
      - "8443:8443"
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always
    networks:
      www:
        aliases:
          - $DOMAIN_NAME
    volumes:
      - wordpress_data:/var/www

networks:
  mysql: {}
  redis: {}
  www: {}

volumes:

  db_data:
    driver: local
    driver_opts:
      type: none
      device: $VOLUME_BASE_DIR/db
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: $VOLUME_BASE_DIR/wp
      o: bind

  git_data:
    driver: local
    driver_opts:
      type: none
      device: $VOLUME_BASE_DIR/git
      o: bind
